graphql:
  tools:
    schema-location-pattern: "**/*.graphql"
  servlet:
    max-query-depth: 15
  playground:
    enabled: true
voyager:
  enabled: true
server:
  servlet:
    encoding:
      force: true
      charset: utf-8
spring:
  servlet:
    multipart:
      max-file-size: 5MB